# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 723f773dc5222a15444ca4a79a697a1537c0a7fe14403b576483c2cc60d38e406a89304fc2c6ad2c3fbaaa8724d8c560a89d9c0d26b878c4ddd0636c16e0738c

test:
  secret_key_base: e37af17f33c4b4b7d034f29d26f0f9bf0756e3793624214f61224e3847121b9ef93df46cd89b0c3e79606c6c10466d9bc70420d160932995d1de8fc761fb9eb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
